## Numpy

In [1]:
import numpy as np

### Basic exercises 

####  Ceate a 1D array of numbers from 0 to 9

In [3]:
# Solution
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Create a 3×3 numpy array of all True’s

In [5]:
# Solution
x=np.full((3, 3), True)
x

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### Replace all odd numbers in arr with -1

In [6]:
# Input
arr = np.arange(10)
# Solution
arr[arr%2==0] = -1
arr

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

#### Convert a 1D array to a 2D array with 2 rows

In [14]:
# Input
arr = np.arange(10)
print(arr)

# Solution
arr2d=np.reshape(arr,(2,-1))
arr2d

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Stack arrays a and b vertically and then horizontally

In [19]:
# Input
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

# Solution
vert=np.vstack((a,b))
orr=np.hstack((a,b))
print(vert)
print(orr)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


#### Find positions where elements of a and b match

In [20]:
# Input
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Solution
indexes=np.where(a==b)
print(indexes)

(array([1, 3, 5, 7]),)


####  Get all items between 5 and 10 from a

In [22]:
# Input
a = np.arange(15)

# Solutions
new_a=np.where(np.logical_and(a>=5,a<=10))
print(new_a)

(array([ 5,  6,  7,  8,  9, 10]),)


#### Get the positions of top 5 maximum values in a given array a

In [26]:
# Input
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
print(a)

# Solution:

# Indexes
top5=a.argsort()[-5:][::-1]
print("TOP FIVE: ",top5)

# values

y = a.copy() # <----optional, create a copy of the array
y = np.sort(a) # sort array
y = y[::-1] # reverse sort order
y = y[0:5] # take a slice of the first 5
print("TOP FIVE: ",y)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
TOP FIVE:  [15 10  3  7 18]
TOP FIVE:  [48.95256545 44.67477576 42.39403048 41.466785   40.99501269]


#### Compute the min-by-max (i.e. min/max) for each row for given 2d numpy array (see [apply_along_axis](https://numpy.org/doc/stable/reference/generated/numpy.apply_along_axis.html#numpy-apply-along-axis))

In [27]:
# Input
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)

# Solution
new_a=np.min(a, axis = 1)/np.max(a,axis = 1)
print(new_a)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[0.44444444 0.125      0.5        1.         0.11111111]


####  Find the duplicate entries in the given numpy array and mark them as True. First time occurrences should be False.

In [28]:
# Input
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)

# Solution
uniques = np.unique(a, True)[1]
result = a == a
result[uniques] = False
result

Array:  [0 0 3 0 2 4 2 2 2 2]


array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

#### Find the index of 5th repetition of number 1 in x
Make use of numpy.where

In [32]:
# Input
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5
# Soluzione
new_a=np.where(x == 1)[0][4]
print(new_a)

8


#### Compute the moving average of window size 3, for the given 1D array
Make use of numpy.convolve

In [46]:
# Input
arr = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

# Solution
convolve=np.convolve(arr, np.ones(3)/3, mode='valid')
print(convolve)

[6.33333333 6.         5.66666667 4.66666667 3.66666667 2.
 3.66666667 3.        ]


### Iris dataset

#### Import the iris dataset from iris.txt
See np.genfromtxt, load the dataset with dtype=np.str

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [55]:
# Input filepath
FILEPATH = "/content/drive/MyDrive/mlinapp/basics-data/iris.txt"
# Soultion
dataset_iris = np.loadtxt(FILEPATH, delimiter=",", dtype=np.str)
print(dataset_iris)

[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['5.4' '3.4' '1.7' '0.2' 'Iris-setosa']
 ['5.1' '3.7' '1.5' '0.4' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['5.1' '3.3' '1.7' '0.5' 'Iris-setosa']
 ['4.8' '3.4' '1

<ipython-input-55-167b60db0684>:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dataset_iris = np.loadtxt(FILEPATH, delimiter=",", dtype=np.str)


#### Print the unique labels of the dataset

In [57]:
# Solution
unique_labels=np.unique(dataset_iris[:,-1])
print(unique_labels)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


#### Find how many samples (i.e. rows) we have for each unique label

In [65]:
# Solution
unique,counts = np.unique(dataset_iris, return_counts=True)
print(counts)

[ 6 28  7  7  1  1  8  4  7 20 20 26 11  6 12  7  7  6  6 12  6 11  5  9
 14 10 27 12 13  8 12  8  4  4  7  5  6  4  5  3  8  9  7  7  9 11 14 17
  6  3  8 10 12 11 10  5  8  9  4 10  8  5  3 10  3  5  1  1  3  1  1  1
  4  1 50 50 50]


#### Find the mean, median, standard deviation of iris's sepallength (1st column)
See np.genfromtxt, load only the 1st column with the appropiate data type

In [68]:
# Solution
iris = np.genfromtxt(FILEPATH, delimiter=',', dtype='object')
sepallength = np.genfromtxt(FILEPATH, delimiter=',', dtype='float', usecols=[0])
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


####  Find the mean, median, standard deviation of iris's sepallength (1st column) for each unique labels

In [53]:
# Solution


nan nan nan


<ipython-input-53-2b6db64f88a2>:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  iris = np.genfromtxt(unique_labels, delimiter=',', dtype=np.str)


####  Create a new column for volume in iris, where volume is (pi x petallength x sepal_length^2)/3

In [69]:
# Solution
iris_data = np.genfromtxt(FILEPATH, delimiter=',', dtype=object, usecols=[1,2,3,4], skip_header=1)
sepallength = iris_data[:, 0].astype('float')
petallength = iris_data[:, 2].astype('float')
new_column = (np.pi * petallength * (sepallength**2))/3
new_column = new_column[:, np.newaxis]
#new_column
# Add the new column
out = np.hstack([iris_data, new_column])
# output
out[:4]

array([[b'3.0', b'1.4', b'0.2', b'Iris-setosa', 1.8849555921538759],
       [b'3.2', b'1.3', b'0.2', b'Iris-setosa', 2.1446605848506324],
       [b'3.1', b'1.5', b'0.2', b'Iris-setosa', 2.0127136933998613],
       [b'3.6', b'1.4', b'0.2', b'Iris-setosa', 2.714336052701581]],
      dtype=object)

#### Randomly sample iris's species such that setosa is twice the number of versicolor and virginica
See [numpy.random.choice](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html#numpy-random-choice)

In [70]:
# Solution
# Get the species column
species = dataset_iris[:, 4]
np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])
print(np.unique(species_out, return_counts=True))

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'), array([77, 37, 36]))


#### Sort the iris dataset based on sepallength column

In [71]:
# Solution
print(dataset_iris[dataset_iris[:,0].argsort()][:20])

[['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['4.4' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.4' '3.0' '1.3' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.5' '2.3' '1.3' '0.3' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['4.6' '3.2' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.3' 'Iris-setosa']
 ['4.8' '3.4' '1.9' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.1' '1.6' '0.2' 'Iris-setosa']
 ['4.9' '2.4' '3.3' '1.0' 'Iris-versicolor']
 ['4.9' '2.5' '4.5' '1.7' 'Iris-virginica']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']]


#### Find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
# Solution
vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

[Ellipsis]

#### Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset

see [np.argwhere](https://numpy.org/doc/stable/reference/generated/numpy.argwhere.html#numpy-argwhere)

In [73]:
# Solution
np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

array([50])

#### Get the rows having petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [77]:
# Solution
dataset_iris_due = np.genfromtxt(FILEPATH, delimiter=',', dtype='float', usecols=[0,1,2,3])
condition = (dataset_iris_due[:, 2] > 1.5) & (dataset_iris_due[:, 0] < 5.0)
dataset_iris_due[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])